// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ggrok.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	ggrok.proto

It has these top-level messages:
	ClientServer
	InitRequest
	HTTPResponse
	ServerClient
	InitResponse
	HTTPRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Container message for Client -> Server communication. Clients send InitRequest messages to initiate a steam with Server
// Clients encapulate http.Response objects and send them to server.
type ClientServer struct {
	// Types that are valid to be assigned to Clientmsg:
	//	*ClientServer_Initreq
	//	*ClientServer_Httpresp
	Clientmsg isClientServer_Clientmsg `protobuf_oneof:"clientmsg"`
}

func (m *ClientServer) Reset()                    { *m = ClientServer{} }
func (m *ClientServer) String() string            { return proto1.CompactTextString(m) }
func (*ClientServer) ProtoMessage()               {}
func (*ClientServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isClientServer_Clientmsg interface {
	isClientServer_Clientmsg()
}

type ClientServer_Initreq struct {
	Initreq *InitRequest `protobuf:"bytes,1,opt,name=initreq,oneof"`
}
type ClientServer_Httpresp struct {
	Httpresp *HTTPResponse `protobuf:"bytes,2,opt,name=httpresp,oneof"`
}

func (*ClientServer_Initreq) isClientServer_Clientmsg()  {}
func (*ClientServer_Httpresp) isClientServer_Clientmsg() {}

func (m *ClientServer) GetClientmsg() isClientServer_Clientmsg {
	if m != nil {
		return m.Clientmsg
	}
	return nil
}

func (m *ClientServer) GetInitreq() *InitRequest {
	if x, ok := m.GetClientmsg().(*ClientServer_Initreq); ok {
		return x.Initreq
	}
	return nil
}

func (m *ClientServer) GetHttpresp() *HTTPResponse {
	if x, ok := m.GetClientmsg().(*ClientServer_Httpresp); ok {
		return x.Httpresp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ClientServer) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _ClientServer_OneofMarshaler, _ClientServer_OneofUnmarshaler, _ClientServer_OneofSizer, []interface{}{
		(*ClientServer_Initreq)(nil),
		(*ClientServer_Httpresp)(nil),
	}
}

func _ClientServer_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*ClientServer)
	// clientmsg
	switch x := m.Clientmsg.(type) {
	case *ClientServer_Initreq:
		b.EncodeVarint(1<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Initreq); err != nil {
			return err
		}
	case *ClientServer_Httpresp:
		b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Httpresp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ClientServer.Clientmsg has unexpected type %T", x)
	}
	return nil
}

func _ClientServer_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*ClientServer)
	switch tag {
	case 1: // clientmsg.initreq
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(InitRequest)
		err := b.DecodeMessage(msg)
		m.Clientmsg = &ClientServer_Initreq{msg}
		return true, err
	case 2: // clientmsg.httpresp
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(HTTPResponse)
		err := b.DecodeMessage(msg)
		m.Clientmsg = &ClientServer_Httpresp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ClientServer_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*ClientServer)
	// clientmsg
	switch x := m.Clientmsg.(type) {
	case *ClientServer_Initreq:
		s := proto1.Size(x.Initreq)
		n += proto1.SizeVarint(1<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *ClientServer_Httpresp:
		s := proto1.Size(x.Httpresp)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// InitRequest is the initial client request sent to the server.
type InitRequest struct {
	// opportunistically ask for a hostname. Server may still decide to respond
	// with a random ID for hostname.
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto1.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InitRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

// HTTPResponse holds the bytes returned from a call to http.Response.Write(). See: https://golang.org/src/net/http/response.go?s=7618:7661#L229
type HTTPResponse struct {
	Response []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (m *HTTPResponse) Reset()                    { *m = HTTPResponse{} }
func (m *HTTPResponse) String() string            { return proto1.CompactTextString(m) }
func (*HTTPResponse) ProtoMessage()               {}
func (*HTTPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HTTPResponse) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

// Container message for Server -> Client communication. Servers respond to client's InitRequest messages.
// Servers encapulate http.Request and send them to client
type ServerClient struct {
	// Types that are valid to be assigned to Servermsg:
	//	*ServerClient_Initresp
	//	*ServerClient_Httpreq
	Servermsg isServerClient_Servermsg `protobuf_oneof:"servermsg"`
}

func (m *ServerClient) Reset()                    { *m = ServerClient{} }
func (m *ServerClient) String() string            { return proto1.CompactTextString(m) }
func (*ServerClient) ProtoMessage()               {}
func (*ServerClient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isServerClient_Servermsg interface {
	isServerClient_Servermsg()
}

type ServerClient_Initresp struct {
	Initresp *InitResponse `protobuf:"bytes,1,opt,name=initresp,oneof"`
}
type ServerClient_Httpreq struct {
	Httpreq *HTTPRequest `protobuf:"bytes,2,opt,name=httpreq,oneof"`
}

func (*ServerClient_Initresp) isServerClient_Servermsg() {}
func (*ServerClient_Httpreq) isServerClient_Servermsg()  {}

func (m *ServerClient) GetServermsg() isServerClient_Servermsg {
	if m != nil {
		return m.Servermsg
	}
	return nil
}

func (m *ServerClient) GetInitresp() *InitResponse {
	if x, ok := m.GetServermsg().(*ServerClient_Initresp); ok {
		return x.Initresp
	}
	return nil
}

func (m *ServerClient) GetHttpreq() *HTTPRequest {
	if x, ok := m.GetServermsg().(*ServerClient_Httpreq); ok {
		return x.Httpreq
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ServerClient) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _ServerClient_OneofMarshaler, _ServerClient_OneofUnmarshaler, _ServerClient_OneofSizer, []interface{}{
		(*ServerClient_Initresp)(nil),
		(*ServerClient_Httpreq)(nil),
	}
}

func _ServerClient_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*ServerClient)
	// servermsg
	switch x := m.Servermsg.(type) {
	case *ServerClient_Initresp:
		b.EncodeVarint(1<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Initresp); err != nil {
			return err
		}
	case *ServerClient_Httpreq:
		b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Httpreq); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ServerClient.Servermsg has unexpected type %T", x)
	}
	return nil
}

func _ServerClient_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*ServerClient)
	switch tag {
	case 1: // servermsg.initresp
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(InitResponse)
		err := b.DecodeMessage(msg)
		m.Servermsg = &ServerClient_Initresp{msg}
		return true, err
	case 2: // servermsg.httpreq
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(HTTPRequest)
		err := b.DecodeMessage(msg)
		m.Servermsg = &ServerClient_Httpreq{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ServerClient_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*ServerClient)
	// servermsg
	switch x := m.Servermsg.(type) {
	case *ServerClient_Initresp:
		s := proto1.Size(x.Initresp)
		n += proto1.SizeVarint(1<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *ServerClient_Httpreq:
		s := proto1.Size(x.Httpreq)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// InitResponse is the response to a client's initial request.
type InitResponse struct {
	// server defined hostname for the current stream
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
}

func (m *InitResponse) Reset()                    { *m = InitResponse{} }
func (m *InitResponse) String() string            { return proto1.CompactTextString(m) }
func (*InitResponse) ProtoMessage()               {}
func (*InitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InitResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

// HTTPRequest holds the bytes returned from a call to http.Request.Write(). See: https://golang.org/src/net/http/request.go?s=16549:16591#L467
type HTTPRequest struct {
	Request []byte `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (m *HTTPRequest) Reset()                    { *m = HTTPRequest{} }
func (m *HTTPRequest) String() string            { return proto1.CompactTextString(m) }
func (*HTTPRequest) ProtoMessage()               {}
func (*HTTPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HTTPRequest) GetRequest() []byte {
	if m != nil {
		return m.Request
	}
	return nil
}

func init() {
	proto1.RegisterType((*ClientServer)(nil), "proto.ClientServer")
	proto1.RegisterType((*InitRequest)(nil), "proto.InitRequest")
	proto1.RegisterType((*HTTPResponse)(nil), "proto.HTTPResponse")
	proto1.RegisterType((*ServerClient)(nil), "proto.ServerClient")
	proto1.RegisterType((*InitResponse)(nil), "proto.InitResponse")
	proto1.RegisterType((*HTTPRequest)(nil), "proto.HTTPRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GGrok service

type GGrokClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (GGrok_StreamClient, error)
}

type gGrokClient struct {
	cc *grpc.ClientConn
}

func NewGGrokClient(cc *grpc.ClientConn) GGrokClient {
	return &gGrokClient{cc}
}

func (c *gGrokClient) Stream(ctx context.Context, opts ...grpc.CallOption) (GGrok_StreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GGrok_serviceDesc.Streams[0], c.cc, "/proto.gGrok/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gGrokStreamClient{stream}
	return x, nil
}

type GGrok_StreamClient interface {
	Send(*ClientServer) error
	Recv() (*ServerClient, error)
	grpc.ClientStream
}

type gGrokStreamClient struct {
	grpc.ClientStream
}

func (x *gGrokStreamClient) Send(m *ClientServer) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gGrokStreamClient) Recv() (*ServerClient, error) {
	m := new(ServerClient)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GGrok service

type GGrokServer interface {
	Stream(GGrok_StreamServer) error
}

func RegisterGGrokServer(s *grpc.Server, srv GGrokServer) {
	s.RegisterService(&_GGrok_serviceDesc, srv)
}

func _GGrok_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GGrokServer).Stream(&gGrokStreamServer{stream})
}

type GGrok_StreamServer interface {
	Send(*ServerClient) error
	Recv() (*ClientServer, error)
	grpc.ServerStream
}

type gGrokStreamServer struct {
	grpc.ServerStream
}

func (x *gGrokStreamServer) Send(m *ServerClient) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gGrokStreamServer) Recv() (*ClientServer, error) {
	m := new(ClientServer)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GGrok_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.gGrok",
	HandlerType: (*GGrokServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _GGrok_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ggrok.proto",
}

func init() { proto1.RegisterFile("ggrok.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x3f, 0x53, 0x83, 0x40,
	0x10, 0xc5, 0xc1, 0x99, 0xfc, 0x5b, 0xa8, 0x2e, 0x0d, 0x93, 0xca, 0xa1, 0x31, 0xa6, 0x60, 0x34,
	0x36, 0xb6, 0x6a, 0x21, 0x76, 0xce, 0x25, 0x5f, 0x20, 0x3a, 0x3b, 0x84, 0x89, 0x70, 0xc7, 0xde,
	0x69, 0xe9, 0x67, 0x77, 0xee, 0x1f, 0x5e, 0x9a, 0x54, 0xec, 0xc2, 0xdb, 0xb7, 0xef, 0xb7, 0x40,
	0xd6, 0x34, 0x24, 0x4e, 0x95, 0x24, 0xa1, 0x05, 0x9b, 0xd8, 0x47, 0xf9, 0x0b, 0xf9, 0xcb, 0x57,
	0x8b, 0xbd, 0xde, 0x21, 0xfd, 0x20, 0xb1, 0x0a, 0x66, 0x6d, 0xdf, 0x6a, 0xc2, 0xa1, 0x48, 0xaf,
	0xd3, 0x75, 0xb6, 0x65, 0x4e, 0x5f, 0xbd, 0xf5, 0xad, 0xe6, 0x38, 0x7c, 0xa3, 0xd2, 0x75, 0xc2,
	0x83, 0x88, 0xdd, 0xc3, 0xfc, 0xa8, 0xb5, 0x24, 0x54, 0xb2, 0xb8, 0xb2, 0x03, 0x4b, 0x3f, 0x50,
	0xef, 0xf7, 0xef, 0x1c, 0x95, 0x14, 0xbd, 0xc2, 0x3a, 0xe1, 0xa3, 0xec, 0x39, 0x83, 0xc5, 0xa7,
	0x5d, 0xd9, 0xa9, 0xa6, 0xbc, 0x85, 0x2c, 0x72, 0x66, 0x2b, 0x98, 0x1f, 0x85, 0xd2, 0xfd, 0xa1,
	0x43, 0xbb, 0x7f, 0xc1, 0xc7, 0xbe, 0xdc, 0x40, 0x1e, 0x7b, 0x1a, 0x2d, 0xf9, 0xda, 0x6a, 0x73,
	0x3e, 0xf6, 0x06, 0xcb, 0x01, 0x39, 0x38, 0x13, 0xd3, 0x25, 0x56, 0xd2, 0x73, 0x2d, 0xcf, 0xb8,
	0xfe, 0x63, 0x06, 0x99, 0xb9, 0x84, 0x8b, 0x3c, 0x78, 0x30, 0x76, 0x06, 0x36, 0x5e, 0xc2, 0x8b,
	0x0c, 0x96, 0xb2, 0x2b, 0x0d, 0xd6, 0x06, 0xf2, 0xd8, 0xf8, 0x22, 0xd7, 0x0d, 0x64, 0x91, 0x25,
	0x2b, 0x60, 0x46, 0xae, 0xf4, 0x54, 0xa1, 0xdd, 0x3e, 0xc1, 0xa4, 0x79, 0x25, 0x71, 0x62, 0x8f,
	0x30, 0xdd, 0x69, 0xc2, 0x43, 0xc7, 0x02, 0x45, 0xfc, 0x0f, 0x57, 0xe1, 0x65, 0x7c, 0x81, 0x32,
	0x59, 0xa7, 0x77, 0xe9, 0xc7, 0xd4, 0x7e, 0x79, 0xf8, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x38, 0x9d,
	0x16, 0xa9, 0x0b, 0x02, 0x00, 0x00,
}
